### PR TITLE
Initial commit of several metrics and walks

### PR DESCRIPTION
**Pull request by robgarden**

### CODE REVIEW

**Comment by robgarden** [comment]
@gpampara @filinep please review when you get a chance. I will add some examples and fill out the README later this week.

**Comment by gpampara** [comment]
It looks mostly fine to to me. You sure you want the package `fla` under the package `cilib`? I'd probable just use `fla`, regardless of the fact that there are references to `cilib` (the library) in the build definition itself.

The only other thing would be that perhaps we use the infix notation for the uses of `\/`? Like `String \/ NonEmptyList[Int]`, or whatever the case is

**Comment by robgarden** [comment]
@gpampara Yes i wasn't sure about the `cilib` package. I based the repo off `benchmarks` so I think we should remove `cilib` there too for consistency.

I'll use the infix notation for `\/`, didn't know it existed.

**Comment by gpampara** [comment]
@robgarden that sounds fine to me.

**Comment by robgarden** [comment]
@gpampara Okay the examples are added. I've also split the project up, similar to cilib. Basically reused `build.sbt` from cilib too but left out the publish settings.

**Comment by gpampara** [comment]
@robgarden Seems fine. I think we should merge this and get some feedback before we push to central. We can make whatever changes are then needed once the PR is closed.

**Pull request merged**
